### ISSUE TITLE
[Wagmi]: pending transaction icon

### ISSUE THREAD

**Issue by david30907d** [all-weather-protocol/all-weather-frontend#17]
# Problem

現在你在 all weather 送出交易時，有個 pop up 會直接說 transaction succeeded. 但其實那個 transaction 還在 pending 階段，需要用個 pending icon 顯示他還在跑，直到 block 真的被區塊鏈挖出來才能說完成！

# Solution

可能可以用這個 [hook](https://wagmi.sh/react/hooks/useWatchPendingTransactions) 但不是太確定。

這個 [block](https://github.com/all-weather-protocol/all-weather-frontend/blob/147091b84c56f80ff283efa91056dce566d3efe4/pages/views/ZapInButton.jsx#L119-L122) 需要調整，其實這裡的 onSuccess 只是代表你成功送出 transaction 但是這個 transaction 本身還沒被區塊鏈接受！

# Resources

use Wagmi this library

# Examples

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/7d10ddb7-bc6a-4c22-a252-aed0c22ebdb2)

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/484477ab-405c-47c0-a862-cf73b3e097b8)

**Comment by fantzulin** [comment]
ZapInButton 目前的 status icon 已修改完成。

ZapOutButton 的 status 是用 wagmi 的 [useWaitForTransaction](https://wagmi.sh/react/hooks/useWaitForTransaction) 來追蹤 Transaction 的狀態，status: 'success' 表示成功寫入區塊鏈，成功後用 Ant Design 的 [message](https://ant.design/components/message-cn) 顯示成功訊息。

目前遇到的問題：使用者點擊 Withdraw 按鈕，Approved 的訊息跳了 3 次，應該只能出現 1 次。
嘗試解決方案 1：使用 wagmi 的 [useTransaction](https://wagmi.sh/react/hooks/useTransaction) 轉帳，追蹤 Transaction 的狀態，status: 'success' 時顯示訊息，有成功顯示，而且只有 1 次。

**Comment by fantzulin** [comment]
ClaimButton
追蹤 claim 的 Transaction  狀態 "成功" 顯示成功訊息，目前已修改成功。
