### ISSUE TITLE
[web3] add a slippage UI component for deposit and withdraw

### ISSUE THREAD

**Issue by david30907d** [all-weather-protocol/all-weather-frontend#19]
# Problem

目前我們不能讓 user 指定 slippage, 但是主流的服務都能讓 advanced user 自己選擇想要承受多少滑點

# Solution

自由決定想用怎樣的樣式去呈現

- [ ] add a slippage components
    - [x] deposit
    - [ ] withdraw
- [x] need to pass this slippage param into smart contract function call

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/176d683d-6d23-4d22-8525-eb1a31c67d84)
![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/6d01a58c-aea9-4f2d-aa90-9eca0dc8fac6)

# Resources
some examples
1. https://kyberswap.com/swap/arbitrum
2. https://app.1inch.io/#/42161/simple/swap/ETH/settings

**Comment by fantzulin** [comment]
[_callbackAfterApprove](https://github.com/all-weather-protocol/all-weather-frontend/blob/main/pages/views/ZapInButton.jsx#L256) function
