### ISSUE TITLE
Unit-test

### ISSUE THREAD

**Issue by david30907d** [all-weather-protocol/all-weather-frontend#53]
# Problem

現在的 CI 非常簡陋，所以有寫錯也很難在 deploy 前被檢查到，都需要依賴人工。但軟體業就是需要用自動化來減少人工降低成本！

## Solution

https://medium.com/%E6%89%8B%E5%AF%AB%E7%AD%86%E8%A8%98/nextjs-testing-tutorial-1-ed4b27563761

**Comment by fantzulin** [comment]
使用 Jest 時會因為無法支援 import 語句的關係，導致 import wagmi 出現 error，用盡各種方法轉譯還是失敗，最後決定改用 [Vitest](https://vitest.dev/)，Setting up Vitest with Next.js [Quickstart](https://nextjs.org/docs/app/building-your-application/testing/vitest#quickstart)
