### ISSUE TITLE
[給新手] show the corresponding currency according to user's IP

### ISSUE THREAD

**Issue by david30907d** [all-weather-protocol/all-weather-frontend#63]
# Problem

Right now, the interests showing in the landing page is using US and NT dollars. We need to show other currencies for other countries's users.

## Solution

1. <https://ip-api.com/>
2. <https://api.exchangerate-api.com/v4/latest/USD>

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/d7d1353b-194f-4aa6-90c3-7b8a9e08bef3)

ip-api provides currency field. We can get the value from `1` and then multiply its exchange rate accordingly

## Scopes

This task is entry level

- [ ] understand the basic of JS `fetch`
- [ ] get familiar with`UserBalanceInfo.jsx` this module

**Comment by fantzulin** [comment]
[IP Geolocation - JSON endpoint](https://ip-api.com/docs/api:json)
[Open Access Endpoint](https://www.exchangerate-api.com/docs/free)
