### ISSUE TITLE
[Feat]: 用 DB 紀錄我們每個月實際賺到多少利息

### ISSUE THREAD

**Issue by david30907d** [all-weather-protocol/all-weather-frontend#88]
# Problem

目前，雖然我們有根據 APR 推算你這個月可能可以拿到的收益，但這是根據現在的 APR 去推算的，並不是真實收益；我們這個月的哇跨收益要完整過完一個月才知道。如果有辦法更清楚地知道這個策略一個月可以讓我們賺到多少錢，這樣就更有底氣大膽發薪水了~

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/758fe3c4-e741-49c9-aaac-8fdfcdcd4daa)

## Solution

類似這樣，需要一個專屬於每個人的 historical chart, 紀錄我們每個月的收益

![Image](https://github.com/all-weather-protocol/all-weather-frontend/assets/9366404/69725933-e3d7-4a89-9e9d-49f097dfe058)

1. 用 backend 去讀取 user 目前的 claimable rewards, 並且寫到 google sheet 當作 DB: <https://github.com/all-weather-protocol/rebalance_backend/blob/cc7ee809934403d8d1ade5b4ea7adc5869e83ad5/routes_dir/addresses.py#L39-L42>
2. 在網頁上呈現出來：<https://github.com/all-weather-protocol/all-weather-frontend/blob/main/pages/views/HistoricalDataChart.jsx>
3. 在 [pipedream](https://pipedream.com/) 設定 cronjob, 隨你開心可以設定 weekly or monthly 去敲這個 backend endpoint. 每敲一次我們的 DB 就會多一個數據點，historical chart 的圖也多一個點這樣

**Comment by fantzulin** [comment]
[User's Claimable Rewards](https://github.com/all-weather-protocol/all-weather-frontend/blob/main/utils/rebalanceSuggestions.js#L49)

1. 先嘗試用 [pipedream](https://pipedream.com/) 固定對一個 google sheet 寫入一個值
2. 把這一個 sheet 的內容變成一個 json 檔，提供給 browser 訪問
3. 把數據呈現在網頁上

**Comment by fantzulin** [comment]
[How to get google sheet data](https://ithelp.ithome.com.tw/articles/10234325)
